### ISSUE TITLE
wpbt alread exists

### ISSUE THREAD

**Issue by zhjygit** [tandasat/WPBT-Builder#2]
![e517b81fa75a3b59f32c3b5d5c1ec22](https://github.com/tandasat/WPBT-Builder/assets/44870751/ff428812-6cdb-4d85-9307-436716f7e436)
How can I del the existed wpbt?

**Comment by tandasat** [comment]
The tool does not support that.

If you like, you can do it in a couple ways easily:
1. Change [the code](https://github.com/tandasat/WPBT-Builder/blob/main/WpbtTestPkg/WpbtBuilder/WpbtBuilder.c#L372-L383) so that the tool add our table on the top of existing one. Hope Windows uses our table over existing one.
2. Change the signature of the existing ACPI table (first 4 bytes IIRC) using the `mm` command, or by modifying tool's code, to that existing table is invalidated, then run the tool to install ours.

**Comment by zhjygit** [comment]
> The tool does not support that.
> 
> If you like, you can do it in a couple ways easily:
> 
> 1. Change [the code](https://github.com/tandasat/WPBT-Builder/blob/main/WpbtTestPkg/WpbtBuilder/WpbtBuilder.c#L372-L383) so that the tool add our table on the top of existing one. Hope Windows uses our table over existing one.
> 2. Change the signature of the existing ACPI table (first 4 bytes IIRC) using the `mm` command, or by modifying tool's code, to that existing table is invalidated, then run the tool to install ours.

“Windows only consumes one”，How can I modiy the code？
#if (EfiLocateFirstAcpiTable(EFI_ACPI_5_0_PLATFORM_BINARY_TABLE_SIGNATURE) != NULL)
#    {
#        ErrorPrint(L"WPBT already exists. Exiting the program.\n");
#        status = EFI_ACCESS_DENIED;
#1         goto Exit;
#    }
just comments them？

**Comment by zhjygit** [comment]
> 2\. Change the signature of the existing ACPI table (first 4 bytes IIRC) using the `mm` command, or by modifying tool's code, to that existing table is invalidated, then run the tool to install ours.

![image](https://github.com/tandasat/WPBT-Builder/assets/44870751/815a51c4-7cd5-4c92-be55-9a6e8084f945)
This is my wpbt via Firmware tables view tools.
How can I change the 4 bytes of wpbt, what is the address of wpbt acpi? Is it 0x 7d e6 00 18?
