### ISSUE TITLE
wpbt alread exists and modify

### ISSUE THREAD

**Issue by zhjygit** [tandasat/WPBT-Builder#3]
![image](https://github.com/tandasat/WPBT-Builder/assets/44870751/36f8e80f-12d3-4f42-9c1c-2073f0a8bdb0)
This is my wpbt via Firmware tables view tools.
How can I change the 4 bytes of wpbt, what is the address of wpbt acpi? Is it 0x 7d e6 00 18?

#if (EfiLocateFirstAcpiTable(EFI_ACPI_5_0_PLATFORM_BINARY_TABLE_SIGNATURE) != NULL)
#{
#ErrorPrint(L"WPBT already exists. Exiting the program.\n");
#status = EFI_ACCESS_DENIED;
#https://github.com/tandasat/WPBT-Builder/issues/1 goto Exit;

}

just comments them？

**Comment by tandasat** [comment]
I strongly recommend you to study code and the format of ACPI tables. 

Yes, commenting out is what I thought I would try when I answered to your questions, but without an understanding of what I suggested you, you would face another questions you would not know how to resolve on your own. Instead of asking, consider studying, messing around, and taking time to digest code, tools, documents. It is an essential skill for anything anyway. 

Closing this as out of scope of this project.
